const fs = require('fs');
let content = fs.readFileSync('src/routes/docs/markdown/+page.svelte', 'utf8');

content = content.replace(
    'import mermaid from \'mermaid\';\n\timport { onMount, onDestroy } from \'svelte\';\n\timport mermaid from \'mermaid\';\n\timport { onMount, onDestroy } from \'svelte\';',
    'import mermaid from \'mermaid\';\n\timport { onMount, onDestroy } from \'svelte\';'
);
content = content.replace(
    '// Timer for debouncing\n\tlet debounceTimer: ReturnType<typeof setTimeout>;\n\n\tlet isDark = $state(false);\n\tlet observer: MutationObserver | undefined = $state();\n\n\tonMount(() => {\n\t\tisDark = document.documentElement.classList.contains(\'dark\');\n\t\tobserver = new MutationObserver(() => {\n\t\t\tconst newIsDark = document.documentElement.classList.contains(\'dark\');\n\t\t\tif (isDark !== newIsDark) {\n\t\t\t\tisDark = newIsDark;\n\t\t\t}\n\t\t});\n\t\tobserver.observe(document.documentElement, { attributes: true, attributeFilter: [\'class\'] });\n\t});\n\n\tonDestroy(() => {\n\t\tif (observer) observer.disconnect();\n\t});\n\n\t$effect(() => {\n\t\tmermaid.initialize({\n\t\t\tstartOnLoad: false,\n\t\t\ttheme: isDark ? \'dark\' : \'default\'\n\t\t});\n\t});\n\n\tlet isDark = $state(false);\n\tlet observer: MutationObserver | undefined = $state();\n\n\tonMount(() => {\n\t\tisDark = document.documentElement.classList.contains(\'dark\');\n\t\tobserver = new MutationObserver(() => {\n\t\t\tconst newIsDark = document.documentElement.classList.contains(\'dark\');\n\t\t\tif (isDark !== newIsDark) {\n\t\t\t\tisDark = newIsDark;\n\t\t\t}\n\t\t});\n\t\tobserver.observe(document.documentElement, { attributes: true, attributeFilter: [\'class\'] });\n\t});\n\n\tonDestroy(() => {\n\t\tif (observer) observer.disconnect();\n\t});\n\n\t$effect(() => {\n\t\tmermaid.initialize({\n\t\t\tstartOnLoad: false,\n\t\t\ttheme: isDark ? \'dark\' : \'default\'\n\t\t});\n\t});',
    '// Timer for debouncing\n\tlet debounceTimer: ReturnType<typeof setTimeout>;\n\n\tlet isDark = $state(false);\n\tlet observer: MutationObserver | undefined = $state();\n\n\tonMount(() => {\n\t\tisDark = document.documentElement.classList.contains(\'dark\');\n\t\tobserver = new MutationObserver(() => {\n\t\t\tconst newIsDark = document.documentElement.classList.contains(\'dark\');\n\t\t\tif (isDark !== newIsDark) {\n\t\t\t\tisDark = newIsDark;\n\t\t\t}\n\t\t});\n\t\tobserver.observe(document.documentElement, { attributes: true, attributeFilter: [\'class\'] });\n\t});\n\n\tonDestroy(() => {\n\t\tif (observer) observer.disconnect();\n\t});\n\n\t$effect(() => {\n\t\tmermaid.initialize({\n\t\t\tstartOnLoad: false,\n\t\t\ttheme: isDark ? \'dark\' : \'default\'\n\t\t});\n\t});'
);

// Remove duplicate effects for HTML rendering
content = content.replace(
    '// Render HTML when debounced markdown changes\n\t$effect(() => {\n\t\t// Trigger reactivity on isDark change as well\n\t\tconst currentIsDark = isDark; \n\t\tif (debouncedMarkdown !== undefined && debouncedMarkdown !== \'\') {\n\t\t\trenderMarkdown(debouncedMarkdown).then(result => {\n\t\t\t\tconst parser = new DOMParser();\n\t\t\t\tconst doc = parser.parseFromString(result, \'text/html\');\n\t\t\t\tconst mermaidNodes = doc.querySelectorAll(\'code.language-mermaid, code.hljs.language-mermaid\');\n\t\t\t\t\n\t\t\t\tif (mermaidNodes.length === 0) {\n\t\t\t\t\thtml = result;\n\t\t\t\t\treturn;\n\t\t\t\t}\n\n\t\t\t\tPromise.all(Array.from(mermaidNodes).map(async (node, i) => {\n\t\t\t\t\tconst text = node.textContent || \'\';\n\t\t\t\t\tconst pre = node.parentElement;\n\t\t\t\t\tif (pre && pre.tagName.toLowerCase() === \'pre\') {\n\t\t\t\t\t\ttry {\n\t\t\t\t\t\t\tconst { svg } = await mermaid.render(`mermaid-${Date.now()}-${i}`, text);\n\t\t\t\t\t\t\tpre.outerHTML = `<div class=\"mermaid-diagram flex justify-center my-4\">${svg}</div>`;\n\t\t\t\t\t\t} catch (e: any) {\n\t\t\t\t\t\t\tpre.outerHTML = `<div class=\"text-red-500 border border-red-500 p-4 rounded my-4 bg-red-50 dark:bg-red-900/20 font-mono text-sm overflow-auto\">Mermaid Syntax Error: ${e.message}</div>`;\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t})).then(() => {\n\t\t\t\t\thtml = doc.body.innerHTML;\n\t\t\t\t});\n\t\t\t});\n\t\t} else {\n\t\t\thtml = \'\';\n\t\t}\n\t});\n\n\t// Render HTML when debounced markdown changes\n\t$effect(() => {\n\t\t// Trigger reactivity on isDark change as well\n\t\tconst currentIsDark = isDark; \n\t\tif (debouncedMarkdown !== undefined && debouncedMarkdown !== \'\') {\n\t\t\trenderMarkdown(debouncedMarkdown).then(result => {\n\t\t\t\tconst parser = new DOMParser();\n\t\t\t\tconst doc = parser.parseFromString(result, \'text/html\');\n\t\t\t\tconst mermaidNodes = doc.querySelectorAll(\'code.language-mermaid, code.hljs.language-mermaid\');\n\t\t\t\t\n\t\t\t\tif (mermaidNodes.length === 0) {\n\t\t\t\t\thtml = result;\n\t\t\t\t\treturn;\n\t\t\t\t}\n\n\t\t\t\tPromise.all(Array.from(mermaidNodes).map(async (node, i) => {\n\t\t\t\t\tconst text = node.textContent || \'\';\n\t\t\t\t\tconst pre = node.parentElement;\n\t\t\t\t\tif (pre && pre.tagName.toLowerCase() === \'pre\') {\n\t\t\t\t\t\ttry {\n\t\t\t\t\t\t\tconst { svg } = await mermaid.render(`mermaid-${Date.now()}-${i}`, text);\n\t\t\t\t\t\t\tpre.outerHTML = `<div class=\"mermaid-diagram flex justify-center my-4\">${svg}</div>`;\n\t\t\t\t\t\t} catch (e: any) {\n\t\t\t\t\t\t\tpre.outerHTML = `<div class=\"text-red-500 border border-red-500 p-4 rounded my-4 bg-red-50 dark:bg-red-900/20 font-mono text-sm overflow-auto\">Mermaid Syntax Error: ${e.message}</div>`;\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t})).then(() => {\n\t\t\t\t\thtml = doc.body.innerHTML;\n\t\t\t\t});\n\t\t\t});\n\t\t} else {\n\t\t\thtml = \'\';\n\t\t}\n\t});',
    '// Render HTML when debounced markdown changes\n\t$effect(() => {\n\t\t// Trigger reactivity on isDark change as well\n\t\tconst currentIsDark = isDark; \n\t\tif (debouncedMarkdown !== undefined && debouncedMarkdown !== \'\') {\n\t\t\trenderMarkdown(debouncedMarkdown).then(result => {\n\t\t\t\tconst parser = new DOMParser();\n\t\t\t\tconst doc = parser.parseFromString(result, \'text/html\');\n\t\t\t\tconst mermaidNodes = doc.querySelectorAll(\'code.language-mermaid, code.hljs.language-mermaid\');\n\t\t\t\t\n\t\t\t\tif (mermaidNodes.length === 0) {\n\t\t\t\t\thtml = result;\n\t\t\t\t\treturn;\n\t\t\t\t}\n\n\t\t\t\tPromise.all(Array.from(mermaidNodes).map(async (node, i) => {\n\t\t\t\t\tconst text = node.textContent || \'\';\n\t\t\t\t\tconst pre = node.parentElement;\n\t\t\t\t\tif (pre && pre.tagName.toLowerCase() === \'pre\') {\n\t\t\t\t\t\ttry {\n\t\t\t\t\t\t\tconst { svg } = await mermaid.render(`mermaid-${Date.now()}-${i}`, text);\n\t\t\t\t\t\t\tpre.outerHTML = `<div class=\"mermaid-diagram flex justify-center my-4\">${svg}</div>`;\n\t\t\t\t\t\t} catch (e: any) {\n\t\t\t\t\t\t\tpre.outerHTML = `<div class=\"text-red-500 border border-red-500 p-4 rounded my-4 bg-red-50 dark:bg-red-900/20 font-mono text-sm overflow-auto\">Mermaid Syntax Error: ${e.message}</div>`;\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t})).then(() => {\n\t\t\t\t\thtml = doc.body.innerHTML;\n\t\t\t\t});\n\t\t\t});\n\t\t} else {\n\t\t\thtml = \'\';\n\t\t}\n\t});'
);


fs.writeFileSync('src/routes/docs/markdown/+page.svelte', content);
