import { describe, it, expect } from 'vitest';
import { ReportExporter, type ExportConfig, type ExportData } from '../ReportExporter';

describe('ReportExporter', () => {
    it('generates HTML with correct sections based on config', async () => {
        const config: ExportConfig = {
            title: 'Test Report',
            theme: 'light',
            includeAiInsight: true,
            includeChart: true,
            includePivot: true,
            includeSql: true,
            includeRawData: true
        };

        const data: ExportData = {
            aiInsight: '<p>Insight generated</p>',
            chartBase64: 'data:image/png;base64,chart_data',
            pivotResult: {
                columns: ['Category', 'Value'],
                rows: [
                    { 'Category': 'A', 'Value': 10 },
                    { 'Category': 'B', 'Value': 20 }
                ]
            },
            pivotChartBase64: 'data:image/png;base64,pivot_chart_data',
            generatedSql: 'SELECT * FROM table LIMIT 10;',
            rawResult: {
                columns: ['id', 'name'],
                rows: [
                    { id: 1, name: 'Alice' },
                    { id: 2, name: 'Bob' }
                ]
            }
        };

        const html = await ReportExporter.generateHtml(config, data);

        // Core tags
        expect(html).toContain('<!DOCTYPE html>');
        expect(html).toContain('<title>Test Report</title>');
        expect(html).toContain('<h1>Test Report</h1>');

        // AI Insight
        expect(html).toContain('<h2>AI Insight</h2>');
        expect(html).toContain('<p>Insight generated</p>'); // Note: AI insight is not escaped as it is pre-rendered HTML

        // Main Chart
        expect(html).toContain('<h2>Chart</h2>');
        expect(html).toContain('src="data:image/png;base64,chart_data"');

        // Pivot Table and Chart
        expect(html).toContain('<h2>Pivot Table</h2>');
        expect(html).toContain('src="data:image/png;base64,pivot_chart_data"');
        expect(html).toContain('<th>Category</th>');
        expect(html).toContain('<th>Value</th>');
        expect(html).toContain('<td>A</td>');
        expect(html).toContain('<td>10</td>');

        // SQL
        expect(html).toContain('<h2>Generated SQL</h2>');
        expect(html).toContain('SELECT * FROM table LIMIT 10;');

        // Raw Data
        expect(html).toContain('<h2>Raw Data (First 2 rows)</h2>');
        expect(html).toContain('<th>id</th>');
        expect(html).toContain('<th>name</th>');
        expect(html).toContain('<td>Alice</td>');
        expect(html).toContain('<td>Bob</td>');

        // Branding
        expect(html).toContain('Generated by <a href="https://localmind.dev"');
    });

    it('respects the theme configuration', async () => {
        const config: ExportConfig = {
            title: 'Test Report',
            theme: 'dark',
            includeAiInsight: false,
            includeChart: false,
            includePivot: false,
            includeSql: false,
            includeRawData: false
        };

        const data: ExportData = {};

        const html = await ReportExporter.generateHtml(config, data);

        expect(html).toContain('--bg-color: #1a202c;');
        expect(html).toContain('--text-color: #e2e8f0;');
    });

    it('handles missing data gracefully', async () => {
        const config: ExportConfig = {
            title: 'Test Report',
            theme: 'light',
            includeAiInsight: true,
            includeChart: true,
            includePivot: true,
            includeSql: true,
            includeRawData: true
        };

        const data: ExportData = {}; // No data provided despite config requesting it

        const html = await ReportExporter.generateHtml(config, data);

        // Even though config includes it, sections shouldn't render if data is missing
        expect(html).not.toContain('<h2>AI Insight</h2>');
        expect(html).not.toContain('<h2>Chart</h2>');
        expect(html).not.toContain('<h2>Pivot Table</h2>');
        expect(html).not.toContain('<h2>Generated SQL</h2>');
        expect(html).not.toContain('<h2>Raw Data');
    });
});
